"""Initial schema: users and trades

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-08

Hand-written rather than autogenerated so that every constraint is explicit and
reviewable - in particular the two UNIQUE indexes on ``trades`` that make
duplicate protection a database guarantee rather than an application promise.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        # Only ever a bcrypt hash; the plaintext password is never stored.
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
    )
    # UNIQUE: one account per email address, enforced by the database.
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        # THE idempotency key. This UNIQUE index is what makes it impossible
        # for two concurrent requests carrying the same TradingView signal to
        # both create a trade.
        sa.Column("signal_id", sa.String(length=64), nullable=False),
        # Deterministically derived from signal_id and sent to Binance as
        # newClientOrderId; also the handle reconciliation uses to ask Binance
        # what happened to an order after a timeout.
        sa.Column("client_order_id", sa.String(length=36), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column(
            "side",
            # native_enum=False -> VARCHAR + CHECK constraint instead of a
            # PostgreSQL ENUM type, so adding a value later is an ordinary
            # migration rather than an ALTER TYPE.
            sa.Enum(
                "BUY",
                "SELL",
                name="orderside",
                native_enum=False,
                length=8,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "order_type",
            sa.String(length=20),
            server_default=sa.text("'MARKET'"),
            nullable=False,
        ),
        # NUMERIC, never float: order quantities must round-trip exactly.
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "UNKNOWN",
                "NEW",
                "PARTIALLY_FILLED",
                "FILLED",
                "CANCELLED",
                "REJECTED",
                "EXPIRED",
                "FAILED",
                name="tradestatus",
                native_enum=False,
                length=20,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("binance_order_id", sa.BigInteger(), nullable=True),
        sa.Column("binance_status", sa.String(length=32), nullable=True),
        sa.Column(
            "executed_quantity", sa.Numeric(precision=28, scale=12), nullable=True
        ),
        sa.Column(
            "cumulative_quote_quantity",
            sa.Numeric(precision=28, scale=12),
            nullable=True,
        ),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_trades_user_id_users",
            # Deleting a user removes their trades rather than leaving orphans.
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_trades"),
    )

    op.create_index("ix_trades_signal_id", "trades", ["signal_id"], unique=True)
    op.create_index(
        "ix_trades_client_order_id", "trades", ["client_order_id"], unique=True
    )
    op.create_index("ix_trades_user_id", "trades", ["user_id"])
    op.create_index("ix_trades_status", "trades", ["status"])
    op.create_index("ix_trades_binance_order_id", "trades", ["binance_order_id"])
    op.create_index("ix_trades_created_at", "trades", ["created_at"])
    # Serves "list my trades, newest first" (GET /trades).
    op.create_index(
        "ix_trades_user_id_created_at", "trades", ["user_id", "created_at"]
    )
    # Serves "find everything still in flight" (reconciliation).
    op.create_index(
        "ix_trades_status_created_at", "trades", ["status", "created_at"]
    )


def downgrade() -> None:
    op.drop_index("ix_trades_status_created_at", table_name="trades")
    op.drop_index("ix_trades_user_id_created_at", table_name="trades")
    op.drop_index("ix_trades_created_at", table_name="trades")
    op.drop_index("ix_trades_binance_order_id", table_name="trades")
    op.drop_index("ix_trades_status", table_name="trades")
    op.drop_index("ix_trades_user_id", table_name="trades")
    op.drop_index("ix_trades_client_order_id", table_name="trades")
    op.drop_index("ix_trades_signal_id", table_name="trades")
    op.drop_table("trades")

    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
